map_type: costmap

obstacle_range: 25.0
raytrace_range: 30.0

transform_tolerance: 0.3

# robot_radius: 0.25
# footprint: [[-0.22, -0.20], [-0.22, 0.20], [0.22, 0.20], [0.22, -0.20]] # x = 0.42 y = 0.38
footprint: [[-0.18, -0.18], [-0.18, 0.18], [0.18, 0.18], [0.18, -0.18]] # x = 0.42 y = 0.38
inflation_radius: 0.65

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}
